name: sugarstore
version: 0.3.2
description: Demonstrates how to use the `kopek kodu bandı` plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_bluetooth_serial: ^0.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/pet_logo_24dp.png"
  min_sdk_android: 21 # android min sdk min:16